### ISSUE TITLE
Làm giao diện  trang cá nhân

### ISSUE THREAD

**Issue by minhduc180699** [vuggg/INT2208-7-2019#3]

**Comment by minhduc180699** [comment]
- [ ] Tạo các bố cục cho trang Web.
- [ ] Tạo các liên kết,button,input,.. cho trang Web.
- [ ] Dùng CSS và Boostrap để trang trí.

**Comment by vuggg** [comment]
xong rồi à, chưa xong thì bỏ tích nhé

**Comment by minhduc180699** [comment]
xong
